In [ ]:
# import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import tree

In [ ]:
# membaca dataset
dataset = pd.read_excel("Data Prestasi Siswa.xlsx")

In [ ]:
print(dataset)

   No. JenisKelamin TingkatPendidikan KeaktifanEkstrakurikuler  \
0    1    Laki-laki               SMP                       Ya   
1    2    Perempuan               SMP                    Tidak   
2    3    Laki-laki               SMP                       Ya   
3    4    Perempuan               SMP                       Ya   
4    5    Laki-laki               SMP                    Tidak   
5    6    Perempuan               SMP                    Tidak   
6    7    Laki-laki               SMA                       Ya   
7    8    Perempuan               SMA                    Tidak   
8    9    Laki-laki               SMA                       Ya   

  PrestasiAkademik  
0             Baik  
1       Cukup Baik  
2             Baik  
3             Baik  
4       Cukup Baik  
5       Cukup Baik  
6             Baik  
7             Baik  
8             Baik  


In [ ]:
dataset.head()

No. JenisKelamin TingkatPendidikan KeaktifanEkstrakurikuler  \
0    1    Laki-laki               SMP                       Ya   
1    2    Perempuan               SMP                    Tidak   
2    3    Laki-laki               SMP                       Ya   
3    4    Perempuan               SMP                       Ya   
4    5    Laki-laki               SMP                    Tidak   

  PrestasiAkademik  
0             Baik  
1       Cukup Baik  
2             Baik  
3             Baik  
4       Cukup Baik

In [ ]:
# mengubah kelas (kolom) dari string ke unique-Integer
dataset["PrestasiAkademik"] = pd.factorize(dataset.PrestasiAkademik)[0]


In [ ]:
# mengubah kelas (INSTITUSI) dari string ke unique-Integer
dataset["JenisKelamin"] = pd.factorize(dataset.JenisKelamin)[0]

In [ ]:
dataset["TingkatPendidikan"] = pd.factorize(dataset.TingkatPendidikan)[0]

In [ ]:
dataset["KeaktifanEkstrakurikuler"] = pd.factorize(dataset.KeaktifanEkstrakurikuler)[0]

In [ ]:
dataset.head()

No.  JenisKelamin  TingkatPendidikan  KeaktifanEkstrakurikuler  \
0    1             0                  0                         0   
1    2             1                  0                         1   
2    3             0                  0                         0   
3    4             1                  0                         0   
4    5             0                  0                         1   

   PrestasiAkademik  
0                 0  
1                 1  
2                 0  
3                 0  
4                 1

In [ ]:
print(dataset)

   No.  JenisKelamin  TingkatPendidikan  KeaktifanEkstrakurikuler  \
0    1             0                  0                         0   
1    2             1                  0                         1   
2    3             0                  0                         0   
3    4             1                  0                         0   
4    5             0                  0                         1   
5    6             1                  0                         1   
6    7             0                  1                         0   
7    8             1                  1                         1   
8    9             0                  1                         0   

   PrestasiAkademik  
0                 0  
1                 1  
2                 0  
3                 0  
4                 1  
5                 1  
6                 0  
7                 0  
8                 0  


In [ ]:
dataset = dataset.to_numpy()

In [ ]:
print(dataset)

[[1 0 0 0 0]
 [2 1 0 1 1]
 [3 0 0 0 0]
 [4 1 0 0 0]
 [5 0 0 1 1]
 [6 1 0 1 1]
 [7 0 1 0 0]
 [8 1 1 1 0]
 [9 0 1 0 0]]


In [ ]:
dataTraining = np.concatenate((dataset[0:3, :], dataset[5:8, :]), axis=0)
dataTesting = np.concatenate((dataset[3:5, :], dataset[8:9, :]), axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[1 0 0 0 0]
 [2 1 0 1 1]
 [3 0 0 0 0]
 [6 1 0 1 1]
 [7 0 1 0 0]
 [8 1 1 1 0]]


6

In [ ]:
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTesting)
len(labelTesting)

[0 1 0]


3

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
model = model.fit(inputTraining, labelTraining)

In [ ]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 1 0]
Hasil Prediksi :  [1 0 0]


In [ ]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, " data")
print("Prediksi Salah :", prediksiSalah, " data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, " %")

Prediksi Benar : 1  data
Prediksi Salah : 2  data
Akurasi : 33.33333333333333  %


In [ ]:
import pydotplus
from sklearn import tree
dot_data = tree.export_graphviz(model, out_file=None)
from IPython.display import Image
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png('ukai.png')

True